export const DEFAULT_APPOINTMENT_DURATION = 30;

export const WORKING_HOURS_CONFIG = {
  MORNING_START: 7,
  MORNING_END: 12,
  AFTERNOON_START: 14,
  AFTERNOON_END: 18,
} as const;

export const APPOINTMENT_SLOTS_PER_HOUR = 2;
